# Generated by Django 5.0.1 on 2024-01-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
