# Generated by Django 5.0.1 on 2024-01-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('copy_right_text', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('phone_number', models.CharField(max_length=11)),
            ],
        ),
    ]
