# Generated by Django 5.0.1 on 2024-02-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0002_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
