# Generated by Django 5.0.1 on 2024-02-05 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0004_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comments.comment'),
        ),
    ]
