# Generated by Django 5.0.1 on 2024-02-05 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
        ('Comments', '0006_remove_reply_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.blog'),
        ),
    ]
