# Generated by Django 5.0.1 on 2024-02-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0008_alter_reply_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='comment',
            new_name='comment_org',
        ),
    ]
