# Generated by Django 5.0.1 on 2024-02-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0010_remove_reply_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='text',
            new_name='re_comment',
        ),
    ]
