# Generated by Django 5.0.1 on 2024-02-08 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0011_rename_text_reply_re_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='comment_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomment', to='Comments.comment'),
        ),
    ]
