# Generated by Django 5.0.1 on 2024-02-09 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0012_alter_reply_comment_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comments.comment'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
