# Generated by Django 5.0.1 on 2024-01-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image_icon', models.ImageField(max_length=1000, upload_to='')),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
    ]
