# Generated by Django 5.0.1 on 2024-01-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('type_of_work', models.CharField(max_length=200)),
                ('image_of_product', models.ImageField(max_length=1000, upload_to='')),
            ],
        ),
    ]
