# Generated by Django 5.0.1 on 2024-01-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(max_length=1000, upload_to='media/images/biography')),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
