# Generated by Django 5.0.1 on 2024-01-10 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0002_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='percent',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100, 'It is wrong!'), django.core.validators.MinValueValidator(0, 'It is wrong!')]),
        ),
    ]
