# Generated by Django 5.0.1 on 2024-01-15 15:23

import Skills.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0003_alter_skill_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='percent',
            field=models.IntegerField(validators=[Skills.validators.max_value_validator, Skills.validators.min_value_validator]),
        ),
    ]
