# Generated by Django 5.0.1 on 2024-01-15 15:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0004_alter_skill_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
    ]
