# Generated by Django 5.0.1 on 2024-01-15 15:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0005_alter_biography_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=2000),
        ),
    ]
