# Generated by Django 5.0.1 on 2024-01-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0008_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
