# Generated by Django 5.0.1 on 2024-01-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0010_remove_experience_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
